// uiuxHandler/styleGuide.ts
// Style guide generation for Screen 2

import { Context } from "../../types/context";
import { memoryService } from "../../../memory";
import { DesignTokens, MOOD_OPTIONS } from "./types";
import { callLLMWithLogging, log } from "./utils";

/**
 * Generate the UI style guide markdown document
 */
export async function generateStyleGuide(context: Context): Promise<string> {
    log('Generating style guide...');

    const uiuxData = context.planningData?.uiuxData;
    if (!uiuxData) {
        return getDefaultStyleGuide();
    }

    const tokens = uiuxData.designTokens;
    if (!tokens) {
        return getDefaultStyleGuide();
    }

    const moodInfo = MOOD_OPTIONS.find(m => m.value === uiuxData.mood);

    const styleGuide = `# UI Style Guide

> Generated by E.L.L.A for **${context.projectName}**
> Last updated: ${new Date().toISOString().split('T')[0]}

---

## 🎨 Design Mood

**${moodInfo?.label || uiuxData.mood}** — ${moodInfo?.description || ''}

${uiuxData.tasteAnalysis?.designSignature || ''}

---

## 🎨 Color Palette

### Primary Colors

| Token | Value | Usage |
|-------|-------|-------|
| Primary | \`${tokens.colors.primary}\` | Main actions, links, focus states |
| Secondary | \`${tokens.colors.secondary}\` | Secondary actions, accents |

### Background & Surface

| Token | Value | Usage |
|-------|-------|-------|
| Background | \`${tokens.colors.background}\` | Page background |
| Surface | \`${tokens.colors.surface}\` | Cards, modals, elevated elements |
| Border | \`${tokens.colors.border}\` | Borders, dividers |

### Text Colors

| Token | Value | Usage |
|-------|-------|-------|
| Primary | \`${tokens.colors.text.primary}\` | Headings, important text |
| Secondary | \`${tokens.colors.text.secondary}\` | Body text |
| Muted | \`${tokens.colors.text.muted}\` | Captions, placeholders |

### Semantic Colors

| Token | Value | Usage |
|-------|-------|-------|
| Success | \`${tokens.colors.success}\` | Success states, confirmations |
| Warning | \`${tokens.colors.warning}\` | Warnings, caution states |
| Error | \`${tokens.colors.error}\` | Errors, destructive actions |

---

## 📝 Typography

### Font Families

\`\`\`css
--font-sans: ${tokens.typography.fontFamily.sans};
--font-mono: ${tokens.typography.fontFamily.mono || 'monospace'};
\`\`\`

### Font Sizes

| Token | Value | Usage |
|-------|-------|-------|
| xs | \`${tokens.typography.fontSize.xs}\` | Small labels, badges |
| sm | \`${tokens.typography.fontSize.sm}\` | Secondary text, captions |
| base | \`${tokens.typography.fontSize.base}\` | Body text |
| lg | \`${tokens.typography.fontSize.lg}\` | Large body, intro text |
| xl | \`${tokens.typography.fontSize.xl}\` | H4 headings |
| 2xl | \`${tokens.typography.fontSize['2xl']}\` | H3 headings |
| 3xl | \`${tokens.typography.fontSize['3xl']}\` | H2 headings |
| 4xl | \`${tokens.typography.fontSize['4xl'] || '2.25rem'}\` | H1 headings |

### Font Weights

| Token | Value | Usage |
|-------|-------|-------|
| normal | \`${tokens.typography.fontWeight.normal}\` | Body text |
| medium | \`${tokens.typography.fontWeight.medium}\` | Emphasized text |
| semibold | \`${tokens.typography.fontWeight.semibold}\` | Subheadings |
| bold | \`${tokens.typography.fontWeight.bold}\` | Headings |

---

## 📐 Spacing

| Token | Value | Usage |
|-------|-------|-------|
| xs | \`${tokens.spacing.xs}\` | Tight spacing |
| sm | \`${tokens.spacing.sm}\` | Small gaps |
| md | \`${tokens.spacing.md}\` | Default spacing |
| lg | \`${tokens.spacing.lg}\` | Large gaps |
| xl | \`${tokens.spacing.xl}\` | Section spacing |
| 2xl | \`${tokens.spacing['2xl']}\` | Page sections |

---

## 🔲 Border Radius

| Token | Value | Usage |
|-------|-------|-------|
| none | \`${tokens.borderRadius.none}\` | Sharp corners |
| sm | \`${tokens.borderRadius.sm}\` | Subtle rounding |
| md | \`${tokens.borderRadius.md}\` | Default rounding |
| lg | \`${tokens.borderRadius.lg}\` | Cards, modals |
| xl | \`${tokens.borderRadius.xl}\` | Large elements |
| full | \`${tokens.borderRadius.full}\` | Pills, circles |

---

## 🌓 Shadows

| Token | Value |
|-------|-------|
| sm | \`${tokens.shadows.sm}\` |
| md | \`${tokens.shadows.md}\` |
| lg | \`${tokens.shadows.lg}\` |
${tokens.shadows.glow ? `| glow | \`${tokens.shadows.glow}\` |` : ''}

---

## 📱 Breakpoints

| Token | Value | Description |
|-------|-------|-------------|
| sm | \`${tokens.breakpoints.sm}\` | Small devices (phones) |
| md | \`${tokens.breakpoints.md}\` | Medium devices (tablets) |
| lg | \`${tokens.breakpoints.lg}\` | Large devices (laptops) |
| xl | \`${tokens.breakpoints.xl}\` | Extra large (desktops) |

---

## 🎭 Animation

### Durations

| Token | Value | Usage |
|-------|-------|-------|
| fast | \`${tokens.animation?.duration.fast || '150ms'}\` | Micro-interactions |
| normal | \`${tokens.animation?.duration.normal || '300ms'}\` | Standard transitions |
| slow | \`${tokens.animation?.duration.slow || '500ms'}\` | Page transitions |

### Easing

| Token | Value |
|-------|-------|
| default | \`${tokens.animation?.easing.default || 'ease'}\` |
| in | \`${tokens.animation?.easing.in || 'ease-in'}\` |
| out | \`${tokens.animation?.easing.out || 'ease-out'}\` |
| inOut | \`${tokens.animation?.easing.inOut || 'ease-in-out'}\` |

---

## 🧩 Component Guidelines

### Buttons

\`\`\`css
/* Primary Button */
.btn-primary {
    background: ${tokens.colors.primary};
    color: white;
    padding: ${tokens.spacing.sm} ${tokens.spacing.lg};
    border-radius: ${tokens.borderRadius.md};
    font-weight: ${tokens.typography.fontWeight.semibold};
    transition: all ${tokens.animation?.duration.fast || '150ms'} ease;
}

.btn-primary:hover {
    opacity: 0.9;
    transform: translateY(-1px);
}

/* Secondary Button */
.btn-secondary {
    background: transparent;
    color: ${tokens.colors.primary};
    border: 1px solid ${tokens.colors.border};
    padding: ${tokens.spacing.sm} ${tokens.spacing.lg};
    border-radius: ${tokens.borderRadius.md};
}
\`\`\`

### Cards

\`\`\`css
.card {
    background: ${tokens.colors.surface};
    border: 1px solid ${tokens.colors.border};
    border-radius: ${tokens.borderRadius.lg};
    padding: ${tokens.spacing.lg};
    box-shadow: ${tokens.shadows.sm};
}
\`\`\`

### Inputs

\`\`\`css
.input {
    background: ${tokens.colors.background};
    border: 1px solid ${tokens.colors.border};
    border-radius: ${tokens.borderRadius.md};
    padding: ${tokens.spacing.sm} ${tokens.spacing.md};
    color: ${tokens.colors.text.primary};
}

.input:focus {
    outline: none;
    border-color: ${tokens.colors.primary};
    box-shadow: 0 0 0 3px ${tokens.colors.primary}20;
}
\`\`\`

---

## ✅ Design Principles

1. **Consistency** — Use design tokens everywhere, avoid magic numbers
2. **Hierarchy** — Clear visual hierarchy with size and weight
3. **Accessibility** — Ensure sufficient color contrast (WCAG AA)
4. **Responsiveness** — Mobile-first approach using breakpoints
5. **Performance** — Subtle animations, avoid excessive shadows

---

*Generated by E.L.L.A • Design system ready for implementation*
`;

    // Store in memory
    memoryService.setSession(context.projectId, 'style_guide', styleGuide);

    log('Style guide generated');
    return styleGuide;
}

function getDefaultStyleGuide(): string {
    return `# UI Style Guide

> Default style guide - no design tokens available

Please complete the UI/UX design process to generate a customized style guide.
`;
}
